# playbook.yaml
---
- name: Create Security Policy
  hosts: panorama
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: Add test pre-rule to Panorama
      paloaltonetworks.panos.panos_security_rule:
        provider:
          # Use variable from inventory file
          ip_address: "{{ ansible_host }}"
          # Use variable from group_vars
          username: "{{ panorama_credentials.username }}"
          password: "{{ panorama_credentials.password }}"
        # Use host_vars for policy information
        rule_name: "{{ rule_name }}"
        rulebase: "{{ rulebase }}"
        description: "{{ description }}"
        source_zone: "{{ source_zone }}"
        destination_zone: "{{ destination_zone }}"
        source_ip: "{{ source_ip }}"
        source_user: "{{ source_user }}"
        destination_ip: "{{ destination_ip }}"
        category: "{{ category }}"
        application: "{{ application }}"
        service: "{{ service }}"
        hip_profiles: "{{ hip_profiles }}"
        # tag_name: "{{ tag_name }}"
        action: "{{ action }}"
        device_group: "{{ device_group }}"
      register: results

    - name: Print results to console
      ansible.builtin.debug:
        msg: "{{ results }}"
